version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data:/data/postgres
      - ./postgres/var:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres/test
    ports:
      - '5433:5432'
